FORMAT: 1A
HOST: http://apics.oracle.com:8001/SpotrebaEnergie/

# SpotrebaEnergie

API které vrací informace o spotřebách energií za různá období.

## Spotřeba za tento měsíc [/usage/current/month/{account_number}]
+ Parameters
    + account_number (number) - Číslo účtu zákazníka

### Spotřeba za tento měsíc [GET]
Vrátí informaci o spotřebě energií za **SOUČASNÝ** měsíc.

+ Response 200 (application/json)

        {
            "číslo zákazníka": "12345",
            "jméno": "Martin Chmelař",
            "spotřeba plynu": "8 m3",
            "platba za plyn": "Kč 110",
            "spotřeba elektřiny": "42 kW",
            "platba za elektřinu": "Kč 85",
            "odběrné místo": "Praha",
            "serviceID": "1234"
        }
        
## Spotřeba za minulý měsíc [/usage/last/month/{account_number}]
+ Parameters
    + account_number (number) - Číslo účtu zákazníka

### Spotřeba za minulý měsíc [GET]
Vrátí informaci o spotřebě energií za **MINULÝ** měsíc.

+ Response 200 (application/json)

        {
            "číslo zákazníka": "12345",
            "jméno": "Martin Chmelař",
            "spotřeba plynu": "15 m3",
            "platba za plyn": "Kč 248",
            "spotřeba elektřiny": "92 kW",
            "platba za elektřinu": "Kč 194",
            "odběrné místo": "Praha",
            "serviceID": "1234"
        }

## Odhad budoucí spotřeby [/estimate/{account_number}]
+ Parameters
    + account_number (number) - Číslo účtu zákazníka

### Výpočet odhadované budoucí spotřeby [GET]
Vrátí odhad spotřeby energie pro daného zákazníka.

+ Response 200 (application/json)

        {
           "číslo zákazníka": "12345",
           "jméno": "Martin Chmelař",
           "spotřeba plynu": "15 m3",
           "platba za plyn": "Kč 248",
           "spotřeba elektřiny": "92 kW",
           "platba za elektřinu": "Kč 194",
           "odběrné místo": "Praha",
           "serviceID": "1234"
        }